trigger:
- main

pool:
  name: Dockernewagent

steps:

- checkout: self

- script: docker build -t calendarapp:latest .
  displayName: "Build Docker Image"

- script: docker rm -f calendarapp
  displayName: "Remove Old Container"
  continueOnError: true

- script: docker run -d --name calendarapp -p 8080:80 calendarapp:latest
  displayName: "Run Docker Container"

- script: docker ps
  displayName: "Show Running Containers"