trigger:
- main

pool:
  name: Dockernewagent

steps:

- checkout: self

- powershell: |
    docker build -t calendarapp:latest .
  displayName: Build Docker Image

- powershell: |
    docker stop calendarapp
    docker rm calendarapp
  continueOnError: true
  displayName: Remove Old Container

- powershell: |
    docker run -d --name calendarapp -p 8080:80 calendarapp:latest
  displayName: Run Docker Container

- powershell: |
    docker ps
  displayName: Show Running Containers